pipeline {
    agent any
    stages {
        stage('Build'){
            steps{
                withMaven(maven: 'maven:3.8.1', mavenSettingsConfig: '3e228a06-8997-47e3-b334-e1b6448398cd'){
                    sh 'mvn clean install'
                }
            }
        }
        stage('Sonarqube analysis'){
            steps{
                withSonarQubeEnv('Sonarqube') {
                    withMaven(maven: 'maven:3.8.1', mavenSettingsConfig: '3e228a06-8997-47e3-b334-e1b6448398cd'){
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }
        stage("Quality gate check") {
            steps {
                timeout(time: 5) {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }
}